### ISSUE TITLE
How do it on My ESXi Lab ?

### ISSUE THREAD

**Issue by Mehran** [Marshall-Hallenbeck/red_team_attack_lab#22]
Great job , Just my question if i have ESXi server LAB can i lunch it on my ESXi ? is have any ovf or something  ?

**Comment by Marshall-Hallenbeck** [comment]
Unfortunately no, this is just locally. When I tried to get it all working to ESXi there was some issues. I might try it again.

I have GOAD deploying to ESXi though, which you can see here: https://github.com/Marshall-Hallenbeck/GOADvSphere
